// Run: node tests/presets.js
// Neutral exact-handler checks. No browser, workbook, network, app server or calculation.
// Synthetic DOM objects test state contracts; real keyboard/layout/download acceptance is separate.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const html=fs.readFileSync(path.join(__dirname,'../src/lic_dsf/web.html'),'utf8');
const script=html.split('<script>')[1].split('</script>')[0],lines=script.split(/\r?\n/);new vm.Script(script);
function code(name){let start=lines.findIndex(l=>l.startsWith('function '+name+'(')||l.startsWith('async function '+name+'('));assert(start>=0,name);if(lines[start].endsWith('}'))return lines[start];let end=start+1;while(end<lines.length&&lines[end]!=='}')end++;return lines.slice(start,end+1).join('\n');}
const checks=[];function pass(name){checks.push({name,passed:true});}const norm=x=>JSON.parse(JSON.stringify(x));
function setup(){const fields={},created=[],revoked=[],status=[];function $(id){return fields[id]??=( {value:'',innerHTML:'',textContent:'',dataset:{},attrs:{},checked:false,disabled:false,children:{},classList:{set:new Set(['hidden']),add(x){this.set.add(x)},remove(x){this.set.delete(x)},toggle(x,on){on??=!this.set.has(x);on?this.set.add(x):this.set.delete(x);return on},contains(x){return this.set.has(x)}},setAttribute(k,v){this.attrs[k]=v},removeAttribute(k){delete this.attrs[k];if(k==='src')delete this.src},querySelector(q){return this.children[q]??={textContent:''}},querySelectorAll(){return []},focus(){},decode(){return Promise.resolve()}})};
const rows=[11,13,15,17,20,22,24,28,30,32,34,36,38],definition={delta_paths:Object.fromEntries(rows.map(r=>[r,Array(21).fill(0)])),terms:null};
const s={$,fields,created,revoked,messages:status,boot:{example_available:false},ctx:{zero:definition,imported:definition,inspection:{input_years:Array.from({length:21},(_,i)=>2024+i),input_specs:rows.map(row=>({row,name:'Driver '+row,units:row===17?'local currency (billion)':'pp'}))},scenarios:[{id:'control'},{id:'case'}]},draft:structuredClone(definition),editorReference:structuredClone(definition),sharedNotes:{},active:{id:'case',revision:2},dirty:false,sha:'a'.repeat(64),sourceGeneration:1,comparisonGeneration:0,contextRecord:{revision:0},contextDirty:false,selection:new Set(['control','case']),comparison:{runs:[{scenario_id:'control',revision:1,result_hash:'c'},{scenario_id:'case',revision:2,result_hash:'d'}]},chartURLs:{},chartsReady:false,exported:false,chartError:false,baselineAcknowledged:false,currentRun:true,knownRuns:new Map([['control',{revision:1,current:true}],['case',{revision:2,current:true}]]),uiBusy:false,calculating:false,journalDirty:false,structuredClone,URL:{createObjectURL(blob){const url='blob:'+created.length;created.push({url,blob});return url},revokeObjectURL(url){revoked.push(url)}},status:(...x)=>status.push(x),document:{querySelectorAll:()=>[]},act:fn=>fn(),attempt:fn=>fn(),renderCases(){},renderEditor(){},showBaseline(){},refreshInputDecorations(){},explanationRows(){return []},explanationHTML(){return ''},esc:x=>String(x??''),setTimeout:fn=>fn()};
$('comparator').value='control';$('periodInput').value='20';$('shareLabel').value='Case label';$('name').value='Case name';s.ctx.scenarios=[{id:'control',name:'Control name',share_label:'Control',revision:1,definition,shared_rationale:{}},{id:'case',name:'Case name',share_label:'Case label',revision:2,definition,shared_rationale:{}}];vm.createContext(s);for(const n of ['builtinInvestmentChoices','sourceCurrent','comparisonRequest','comparisonSnapshot','comparisonTarget','comparisonCurrent','clearCharts','clearComparison','resultSignature','previewBoth','interruptedComparison','updateWorkflow','adjustmentState','sameInput','wasEdited','renderAnnualPath','markDirty','canSwitch','invalidInput','textLength','checkShareLabel','selectedCases','legendRenames','markContextDirty','contextConflict','updateCounters','renderLegendFields','reloadCases','settleCalcState','openCase'])vm.runInContext(code(n),s);
return s;}
function handler(s,id,event='onclick'){vm.runInContext(lines.find(l=>l.startsWith(`$('${id}').${event}=`)),s)}
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return {promise,resolve,reject}}
async function ticks(){for(let i=0;i<32;i++)await Promise.resolve()}
(async()=>{
let state=setup();state.comparison=null;state.selection.clear();state.updateWorkflow();assert.equal(state.$('step4').querySelector('small').textContent,'Select cases to compare');state.knownRuns.clear();state.updateWorkflow();assert.equal(state.$('step4').querySelector('small').textContent,'Needs calculated cases');state.ctx=null;state.updateWorkflow();assert(state.$('nextStepText').textContent.includes('reopen'));state.boot.example_available=true;state.updateWorkflow();assert(state.$('nextStepText').textContent.includes('illustrative example'));pass('progress names missing selection and example invitation matches availability');
let s=setup();for(const [v,k] of [[1,'up'],[-.1,'down'],[0,'zero'],[-0,'zero'],['','empty'],['-','empty'],[null,'empty'],['0.000000001','up']])assert.equal(s.adjustmentState(v).kind,k);assert(s.sameInput('0.1',.1));assert(!s.sameInput('',0));pass('sign cues preserve blank/zero/precision distinctions');
s.updateWorkflow();assert.equal(s.$('step2').dataset.state,'pending');assert.equal(s.$('step3').dataset.state,'done');s.currentRun=false;s.updateWorkflow();assert.equal(s.$('step3').dataset.state,'pending');assert.equal(s.$('step3').querySelector('small').textContent,'Saved · calculate next');s.currentRun=true;s.dirty=true;s.updateWorkflow();assert.equal(s.$('step3').dataset.state,'pending');assert(s.$('compareButton').disabled);pass('progress distinguishes manual baseline review, saved, current and dirty revisions');
for(const id of ['newZero','newImported']){s=setup();handler(s,id);s.$(id).onclick();assert.equal(s.currentRun,false);assert.equal(s.active,null);assert.equal(s.comparison,null);}pass('new and imported drafts reset current-run and comparison state');
s=setup();s.$('builtinInvestmentStatus').textContent='Loaded case as a new unsaved draft.';handler(s,'save');const saved={id:'case',revision:3,definition:s.draft,shared_rationale:{}};s.gather=()=>structuredClone(s.draft);s.request=async p=>p==='/api/save'?saved:{scenarios:[saved]};await s.$('save').onclick();assert(!s.currentRun);assert(!s.knownRuns.get('case').current);assert(!s.selection.has('case'));assert(s.selection.has('control'));assert.equal(s.comparison,null);assert.equal(s.$('builtinInvestmentStatus').textContent,'');pass('no-edit save clears transient teaching notice and invalidates current status and saved-case selection while preserving other cases');
s=setup();handler(s,'save');s.gather=()=>s.draft;s.dirty=true;s.sharedNotes={'20':'unsent'};s.request=async()=>{throw Error('CAS conflict')};await assert.rejects(s.$('save').onclick(),/CAS/);assert(s.dirty);assert.equal(s.sharedNotes['20'],'unsent');assert.equal(s.active.revision,2);pass('failed save preserves draft, notes and revision');
s=setup();const grid={},get=(row,i)=>grid[row+':'+i]??={value:0};s.$('grid').querySelector=q=>{const m=q.match(/data-row="(\d+)".*data-offset="(\d+)"/);return get(m[1],m[2])};s.clearInputError=()=>{};s.renderAnnualPath=()=>{};handler(s,'annualPath','oninput');handler(s,'grid','oninput');for(const row of Object.keys(s.draft.delta_paths)){s.$('periodInput').value=row;for(let i=0;i<21;i++){let value=String((Number(row)*21+i)/100003);s.$('annualPath').oninput({target:{dataset:{yearOffset:String(i)},value}});assert.equal(get(row,i).value,value);assert.equal(s.draft.delta_paths[row][i],value);value=String(-Number(value));s.$('grid').oninput({target:{dataset:{row,offset:String(i)},value}});assert.equal(s.draft.delta_paths[row][i],value)}}const snapshot=structuredClone(s.draft);s.$('periodInput').value='20';s.$('annualPath').oninput({target:{dataset:{yearOffset:'20'},value:''}});assert.equal(s.draft.delta_paths['20'][20],'');assert.equal(get('20',20).value,'');for(const r of Object.keys(snapshot.delta_paths))for(let i=0;i<21;i++)if(r!=='20'||i!==20)assert.equal(s.draft.delta_paths[r][i],snapshot.delta_paths[r][i]);pass('both input handlers preserve all 273 precise values and blank without changing unrelated cells');
for(const order of [[0,1],[1,0]]){s=setup();const pair=[deferred(),deferred()],views=[];s.request=async(p,d)=>p==='/api/compare'?structuredClone(s.comparison):(views.push(d.view),pair[d.view==='standard'?0:1].promise);const p=s.previewBoth();for(const i of order){pair[i].resolve({blob:async()=>({view:i})});await ticks()}await p;assert.deepEqual(views,['standard','briefing']);assert(s.chartsReady);assert.equal(Object.keys(s.chartURLs).length,2);assert(!s.$('chart').classList.contains('hidden'));assert(!s.$('chartBriefing').classList.contains('hidden'));}pass('one logical target accepts both render arrival orders and displays both images');
for(const change of ['dirty','source','selection','context']){s=setup();const d=deferred();s.request=async(p,x)=>p==='/api/compare'?s.comparison:{blob:()=>d.promise};const p=s.previewBoth();if(change==='dirty')s.dirty=true;if(change==='source')s.sourceGeneration++;if(change==='selection')s.selection.delete('case');if(change==='context')s.contextRecord.revision++;d.resolve({});await p;assert.equal(s.created.length,0);assert(!s.chartsReady)}pass('late blob bodies cannot publish across input/source/selection/context changes');
s=setup();s.request=async(p,d)=>p==='/api/compare'?{runs:[{scenario_id:'case',revision:3,result_hash:'new'}]}:{blob:async()=>({})};await s.previewBoth();assert.equal(s.comparison,null);assert.equal(s.created.length,0);assert(s.messages.at(-1)[0].includes('changed'));pass('post-render revision/hash change rejects entire pair before creating URLs');
s=setup();s.request=async(p,d)=>{if(d.view==='briefing')throw Error('render failed');return {blob:async()=>({})}};await assert.rejects(s.previewBoth(),/render failed/);assert(!s.chartsReady);assert.equal(s.created.length,0);pass('one failed view leaves no successful-looking pair');
s=setup();const decode=deferred();s.$('chart').decode=()=>decode.promise;s.$('chartBriefing').decode=()=>decode.promise;s.request=async(p,d)=>p==='/api/compare'?structuredClone(s.comparison):{blob:async()=>({})};const stale=s.previewBoth();await ticks();assert.equal(s.created.length,2);s.dirty=true;s.clearComparison();decode.resolve();await stale;assert(!s.chartsReady);assert.equal(s.revoked.length,2);assert(!s.$('chart').src);pass('nonvacuous stale decode clears images and revokes both created URLs');
s=setup();const olddecode=deferred();s.$('chart').decode=()=>olddecode.promise;s.$('chartBriefing').decode=()=>olddecode.promise;s.request=async(p,d)=>p==='/api/compare'?structuredClone(s.comparison):{blob:async()=>({})};const old=s.previewBoth();await ticks();assert.equal(s.created.length,2);s.$('chart').decode=async()=>{};s.$('chartBriefing').decode=async()=>{};await s.previewBoth();assert(s.chartsReady);const urls=structuredClone(s.chartURLs);olddecode.resolve();await old;assert.deepEqual(norm(s.chartURLs),urls);assert(s.chartsReady);assert(s.revoked.includes('blob:0')&&s.revoked.includes('blob:1'));pass('older decoding pair cannot replace or clear newer accepted previews');
s=setup();handler(s,'calculate');s.withBusy=async fn=>fn();s.openCase=async()=>{s.currentRun=true};s.request=async(p)=>p==='/api/calculate'?{job_id:'job'}:{status:'complete',evidence:{calculation:'computed_unverified'}};let compared;s.compare=async()=>{compared=[...s.selection];assert.equal(s.$('comparator').value,'control')};await s.$('calculate').onclick();assert.deepEqual(compared,['control','case']);assert(!s.calculating);pass('automatic post-calculation comparison preserves selected control and other cases');
s=setup();handler(s,'calculate');s.withBusy=async fn=>fn();s.openCase=async()=>{throw Error('must not overwrite draft')};const job=deferred();s.request=async(p)=>p==='/api/calculate'?{job_id:'job'}:job.promise;const p=s.$('calculate').onclick();await ticks();s.dirty=true;s.draft.delta_paths['20'][0]='1.23456789';job.resolve({status:'complete',evidence:{calculation:'computed_unverified'}});await p;assert(s.dirty);assert.equal(s.draft.delta_paths['20'][0],'1.23456789');assert(s.knownRuns.get('case').current);assert(!s.calculating);pass('late completed calculation retains newer unsaved draft and does not auto compare');
s=setup();handler(s,'save');{const saved={id:'case',revision:3,definition:s.draft,shared_rationale:{}};s.gather=()=>structuredClone(s.draft);let compared=false;s.compare=async()=>{compared=true};s.request=async p=>p==='/api/save'?saved:p.startsWith('/api/scenario')?{scenario:{revision:3},run:{result:{evidence:{calculation:'computed_unverified'}}}}:{scenarios:[saved]};await s.$('save').onclick();assert(s.currentRun);assert(s.knownRuns.get('case').current);assert(s.selection.has('case')&&s.selection.has('control'));assert(compared);assert(s.$('calcState').textContent.includes('no recalculation'));}pass('label or explanation-only save keeps the current calculation, the selection and refreshes the comparison');
s=setup();handler(s,'save');{const saved={id:'case',revision:3,definition:s.draft,shared_rationale:{}};s.gather=()=>structuredClone(s.draft);s.request=async p=>p==='/api/save'?saved:p.startsWith('/api/scenario')?{scenario:{revision:3},run:{result:{evidence:{calculation:'computed_unverified'}}}}:{scenarios:[saved]};s.selection.delete('case');s.compare=async()=>{throw Error('must not compare when the saved case is not selected')};await s.$('save').onclick();assert(s.currentRun);assert(!s.selection.has('case'));}pass('current save does not add the case to the selection or compare uninvited');
s=setup();handler(s,'save');{let sent=false;s.gather=()=>structuredClone(s.draft);s.request=async()=>{sent=true;return {}};for(const [value,pattern] of [['',/1 to 40/],['Reference Baseline',/Reference baseline/],['Control',/already uses/],['a'.repeat(41),/40 characters/],['C:\\budget',/paths/]]){s.$('shareLabel').value=value;await assert.rejects(s.$('save').onclick(),pattern);assert(!sent);}}pass('editor save refuses empty, reserved, duplicate, overlong and path-like legend labels before any request');
s=setup();{const inputs=[{dataset:{legend:'control'},value:'Control'},{dataset:{legend:'case'},value:'Lower growth'}];s.$('legendLabels').querySelectorAll=()=>inputs;let renames=s.legendRenames();assert.deepEqual(norm(renames.map(r=>[r.scenario.id,r.label])),[['case','Lower growth']]);inputs[1].value='  Control ';assert.throws(()=>s.legendRenames(),/already uses/);inputs[1].value='Reference baseline';assert.throws(()=>s.legendRenames(),/Reference baseline/);inputs[1].value='';assert.throws(()=>s.legendRenames(),/1 to 40/);inputs[1].value='Case label';assert.deepEqual(norm(s.legendRenames()),[]);}pass('legend renames are validated against the other selected cases and skip unchanged labels');
s=setup();{s.comparison={runs:[]};s.chartsReady=true;s.chartURLs={standard:'blob:0'};s.markContextDirty();assert(s.contextDirty);assert.equal(s.comparison,null);assert(!s.chartsReady);assert(s.$('chartsStatus').textContent.includes('still show the saved text'));s.updateWorkflow();assert(s.$('json').disabled);assert.equal(s.$('step5').querySelector('small').textContent,'Apply chart text');}pass('a legend or heading edit pauses downloads, keeps the saved previews and states the next action');
s=setup();{s.contextRecord={revision:0};let compared=false;s.compare=async()=>{compared=true};s.readContext=r=>r;s.refreshRunStates=async()=>{};s.renderContext=()=>{};s.request=async p=>p.startsWith('/api/scenario')?{scenario:{...s.ctx.scenarios[1]},run:{result:{evidence:{calculation:'computed_unverified'}}},reasoning:[]}:{chart_context:{label:'Elsewhere',revision:1,workbook_sha256:s.sha},scenarios:s.ctx.scenarios};const handled=await s.contextConflict(Error('The chart context changed. Reload it before saving or exporting.'));assert(handled);assert.equal(s.contextRecord.revision,1);assert(compared);assert(s.messages.at(-1)[0].includes('another tab'));assert.equal(await s.contextConflict(Error('Other failure')),false);}pass('a stale heading from another tab is reloaded and both views refreshed instead of a dead end');
s=setup();{s.contextDirty=true;s.comparison={runs:[]};const handled=await s.contextConflict(Error('The chart context changed. Reload it before saving or exporting.'));assert(handled);assert.equal(s.comparison,null);assert(s.messages.at(-1)[1]===true&&s.messages.at(-1)[0].includes('Keep saved text'));}pass('with unapplied chart text the conflict keeps the draft and names the recovery button');
// R2-CX-04: a swap of two unique labels is a valid final set
s=setup();{const inputs=[{dataset:{legend:'control'},value:'Case label'},{dataset:{legend:'case'},value:'Control'}];s.$('legendLabels').querySelectorAll=()=>inputs;assert.deepEqual(norm(s.legendRenames().map(r=>[r.scenario.id,r.label])),[['control','Case label'],['case','Control']]);inputs[1].value='case label';assert.throws(()=>s.legendRenames(),/already uses/);inputs[0].value='Control';inputs[1].value='control';try{s.legendRenames();assert.fail('expected refusal');}catch(e){assert.equal(e.input,inputs[1]);}}pass('R2-CX-04: label swaps are accepted and the complete final set is checked once');
// R2-CX-02: reloadCases loads a coherent editor snapshot and keeps the journal draft
s=setup();{s.active=structuredClone(s.ctx.scenarios.find(x=>x.id==='case'));s.draft=structuredClone(s.active.definition);s.editorReference=structuredClone(s.draft);s.sharedNotes={'20':'Earlier explanation'};s.currentRun=true;s.journalDirty=true;s.$('reasoning').value='Unsaved journal draft';
 const fresh=structuredClone(s.active);fresh.revision=3;fresh.definition.delta_paths['20'][0]=2;fresh.definition.terms={rate:.05,grace_years:4,maturity_years:9};fresh.shared_rationale={'20':'New explanation from other tab'};fresh.name='Renamed elsewhere';
 s.refreshRunStates=async()=>{s.knownRuns.set('case',{revision:3,current:false});};s.request=async p=>p.startsWith('/api/scenario')?{scenario:fresh,run:null,reasoning:[]}:{scenarios:[s.ctx.scenarios[0],fresh],chart_context:s.contextRecord};
 assert(await s.reloadCases({sha:s.sha,generation:s.sourceGeneration}));assert.equal(s.active.revision,3);assert.equal(s.draft.delta_paths['20'][0],2);assert.deepEqual(norm(s.draft.terms),{rate:.05,grace_years:4,maturity_years:9});assert.deepEqual(norm(s.editorReference),norm(fresh.definition));assert.equal(s.sharedNotes['20'],'New explanation from other tab');assert.equal(s.currentRun,false);assert.equal(s.$('name').value,'Renamed elsewhere');assert.equal(s.$('reasoning').value,'Unsaved journal draft');assert(s.journalDirty);assert.equal(s.$('calcState').textContent,'Calculate this revision to get current results.');}pass('R2-CX-02: reload after chart-text apply carries inputs, financing, explanations, run state and revision together and keeps the journal draft');
s=setup();{s.active=structuredClone(s.ctx.scenarios.find(x=>x.id==='case'));s.dirty=true;s.draft.delta_paths['20'][1]=-0.7;s.request=async()=>({scenarios:s.ctx.scenarios.map(x=>x.id==='case'?{...x,revision:9}:x),chart_context:s.contextRecord});s.refreshRunStates=async()=>{};let opened=false;s.openCase=async()=>{opened=true};assert(await s.reloadCases({sha:s.sha,generation:s.sourceGeneration}));assert(!opened);assert.equal(s.active.revision,2);assert.equal(s.draft.delta_paths['20'][1],-0.7);}pass('R2-CX-02: an unsaved draft is never mixed with a newer revision token');
// R2-CX-01: refused combined apply changes nothing locally and retry uses the same revisions
s=setup();handler(s,'saveChartContext');{s.contextRecord={label:'Old heading',revision:1,workbook_sha256:s.sha};s.$('chartContextLabel').value='https://example.invalid/brief';s.$('legendLabels').querySelectorAll=()=>[{dataset:{legend:'case'},value:'Renamed case'}];s.contextDirty=true;const sent=[];s.request=async(p,d)=>{sent.push([p,d]);throw Error('Use a short chart label; fiscal years are allowed, but file paths, links and control characters are not.');};s.withBusy=async f=>f();s.reloadCases=async()=>{throw Error('must not reload after a refusal')};await assert.rejects(s.$('saveChartContext').onclick(),/short chart label/);assert.equal(sent.length,1);assert.equal(sent[0][0],'/api/chart-text');assert.deepEqual(norm(sent[0][1].labels),[{scenario_id:'case',expected_revision:2,share_label:'Renamed case'}]);assert.deepEqual(norm(sent[0][1].heading),{label:'https://example.invalid/brief'});assert(s.contextDirty);assert.equal(s.contextRecord.revision,1);assert.equal(s.ctx.scenarios[1].revision,2);
 s.request=async(p,d)=>{sent.push([p,d]);return {chart_context:{label:'Fixed heading',revision:2,workbook_sha256:s.sha},scenarios:[{...s.ctx.scenarios[1],revision:3,share_label:'Renamed case'}]};};s.$('chartContextLabel').value='Fixed heading';s.readContext=r=>r;let reloaded=false;s.reloadCases=async()=>{reloaded=true;return true};s.renderContext=()=>{};s.compare=async()=>{};await s.$('saveChartContext').onclick();assert.equal(sent[1][1].labels[0].expected_revision,2);assert.equal(sent[1][1].expected_context_revision,1);assert(!s.contextDirty);assert.equal(s.contextRecord.revision,2);assert(reloaded);}pass('R2-CX-01: labels and heading go in one request; a refusal leaves revisions, drafts and the pending state untouched, and the retry uses the same tokens');
// R2-CX-03: inline calculation status settles from actual state on start failure, job failure and a newer draft
s=setup();handler(s,'calculate');{s.knownRuns.set('case',{revision:2,current:false});s.currentRun=false;s.request=async()=>{throw Error('Calculation resource unavailable');};s.withBusy=async f=>f();await assert.rejects(s.$('calculate').onclick(),/resource unavailable/);assert.equal(s.calculating,false);assert(s.$('calcState').textContent.startsWith('Calculation did not finish: Calculation resource unavailable'));assert(!s.$('calculate').disabled);}pass('R2-CX-03: a refused start clears the inline Calculating text and says what happened');
s=setup();handler(s,'calculate');{s.request=async()=>{throw Error('Another calculation is running. Try again when it finishes.');};s.withBusy=async f=>f();await assert.rejects(s.$('calculate').onclick(),/Another calculation/);assert.equal(s.calculating,false);assert(s.$('calcState').textContent.startsWith('Current calculation available'));}pass('R2-CX-03: a refused start on a case that already has a current result reports that result truthfully');
s=setup();handler(s,'calculate');{s.knownRuns.set('case',{revision:2,current:false});s.currentRun=false;s.request=async p=>p==='/api/calculate'?{job_id:'job'}:{status:'failed',message:'The calculation exceeded its time limit. Saved inputs are retained.'};s.withBusy=async f=>f();await assert.rejects(s.$('calculate').onclick(),/time limit/);assert.equal(s.calculating,false);assert(s.$('calcState').textContent.startsWith('Calculation did not finish: The calculation exceeded'));assert(!s.knownRuns.get('case').current);}pass('R2-CX-03: a failed or interrupted job clears the inline Calculating text');
s=setup();handler(s,'calculate');{const poll=deferred();s.request=async p=>p==='/api/calculate'?{job_id:'job'}:poll.promise;s.withBusy=async f=>f();const run=s.$('calculate').onclick();await ticks();assert(s.$('calcState').textContent.startsWith('Calculating'));s.markDirty();assert(s.$('calcState').textContent.startsWith('Inputs or shared explanations changed'));poll.reject(Error('Calculation could not finish'));await assert.rejects(run,/could not finish/);assert.equal(s.calculating,false);assert(s.$('calcState').textContent.startsWith('Inputs or shared explanations changed'));}pass('R2-CX-03: a failure during a newer draft keeps the draft message instead of overwriting it');
s=setup();handler(s,'calculate');{s.request=async p=>p==='/api/calculate'?{job_id:'job'}:{status:'complete',evidence:{calculation:'review_required'}};s.withBusy=async f=>f();await assert.rejects(s.$('calculate').onclick(),/require review/);assert.equal(s.$('calcState').textContent,'Calculation findings need review; exports are held.');assert(s.knownRuns.get('case').review);}pass('R2-CX-03: a review-required result is shown as such beside the button');
const result={html_sha256:crypto.createHash('sha256').update(html).digest('hex'),scope:'Exact source handlers with neutral synthetic objects; no browser, workbook, engine or API server execution.',checks,passed:checks.length};console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
