// Run with Playwright available and CHROME_EXECUTABLE set to a local Chrome binary.
// All API responses are neutral synthetic fixtures; no workbook or calculation is used.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const out=process.env.QA_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'presets-results-'));
 fs.mkdirSync(out,{recursive:true});
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'presets-browser-'));
 const browser=await chromium.launchPersistentContext(profile,{headless:true,chromiumSandbox:true,ignoreDefaultArgs:true,args:['--headless','--remote-debugging-pipe','--user-data-dir='+profile,'--no-first-run','--no-default-browser-check','--disable-background-networking','about:blank'],executablePath:process.env.CHROME_EXECUTABLE});
 const checks={};
 try{
  await browser.route('**/*',r=>r.abort());
  const page=await browser.newPage();
  let html=fs.readFileSync(path.join(__dirname,'../src/lic_dsf/web.html'),'utf8');
  html=html.replace('<script>','<script>window.fetch=async()=>({json:async()=>({workbooks:[],title:"Scenario tool",note:"",token:"test"})});');
  await page.setContent(html);await page.waitForFunction(()=>typeof boot!=='undefined');
  const setup=async()=>page.evaluate(()=>{
   const rows=[11,13,15,17,20,22,24,28,30,32,34,36,38],zero={delta_paths:Object.fromEntries(rows.map(r=>[r,Array(21).fill(0)])),terms:null};
   ctx={zero,imported:{delta_paths:Object.fromEntries(rows.map(r=>[r,Array(21).fill(7)])),terms:{rate:.08,grace_years:1,maturity_years:9}},baseline_preview:[],inspection:{input_specs:rows.map(r=>({row:r,name:({13:'Primary expenditure',20:'GDP growth',28:'Exports'})[r]||'Input '+r,units:r===20?'percentage points':'points of GDP'})),input_years:Array.from({length:21},(_,i)=>2032+i),customization:{terms:{rate:{value:.04},grace_years:{value:2},maturity_years:{value:10}}}},scenarios:[]};
   sha='a'.repeat(64);contextRecord={workbook_sha256:sha,label:null,revision:0};ctx.chart_context=structuredClone(contextRecord);contextDirty=false;sourceGeneration++;active={id:'saved',revision:1,definition:structuredClone(ctx.imported)};draft=structuredClone(ctx.imported);dirty=false;journalDirty=false;uiBusy=false;calculating=false;comparison={old:true};window.calls=[];request=async(...args)=>{window.calls.push(args);throw Error('Unexpected API call');};window.fetch=async(...args)=>{window.calls.push(args);throw Error('Unexpected fetch');};
   $('reasoning').value='';$('reasoningHistory').innerHTML='<p>Retained journal for saved scenario</p>';$('name').value='Saved scenario';$('illustrativePreset').value='';$('comparisonTable').textContent='Old results';$('comparisonEvidence').textContent='Old evidence';$('chart').classList.remove('hidden');$('editor').classList.remove('hidden');$('editorEmpty').classList.add('hidden');$('presetOptions').open=true;renderEditor();window.originalContext=JSON.stringify(ctx);window.originalActive=JSON.stringify(active);status('');
  });
  for(const [key,row,value] of [['growth','20',-1],['spending','13',1],['exports','28',-1]]){
   await setup();await page.selectOption('#illustrativePreset',key);await page.locator('#usePreset').click();
   const result=await page.evaluate(({row,value})=>({exact:Object.entries(draft.delta_paths).length===13&&Object.entries(draft.delta_paths).every(([r,p])=>p.length===21&&p.every((v,i)=>v===(r===row&&i<3?value:0))),inherited:draft.terms===null&&!$('overrideTerms').checked&&['rate','grace','maturity'].every(id=>$(id).disabled),unsaved:active===null&&dirty&&$('calculate').disabled&&$('workbookSelect').disabled,clean:comparison===null&&$('comparisonTable').innerHTML===''&&$('comparisonEvidence').innerHTML===''&&$('chart').classList.contains('hidden')&&$('reasoning').value===''&&$('reasoningHistory').innerHTML===''&&!journalDirty,unchanged:JSON.stringify(ctx)===window.originalContext&&sha==='a'.repeat(64),noRequests:window.calls.length===0,calendar:$('name').value.includes('2032–2034')&&$('presetYears').textContent==='2032–2034',focus:document.activeElement.id==='name'}),{row,value});
   Object.entries(result).forEach(([n,v])=>{assert.equal(v,true,key+': '+n);checks[key+'_'+n]=v;});
   if(key==='growth'){
    await page.locator('#presetOptions').screenshot({path:path.join(out,'illustrative-starting-points.png')});
    await page.locator('#pdf').click();assert.match(await page.locator('#status').textContent(),/Save or discard/);assert.equal(await page.evaluate(()=>window.calls.length),0);checks.unsaved_export_blocked=true;
   }
  }
  for(const guard of ['dirty','journal','busy','calculating']){
   await setup();await page.selectOption('#illustrativePreset','growth');
   await page.evaluate(g=>{if(g==='dirty')dirty=true;if(g==='journal'){journalDirty=true;$('reasoning').value='Unsaved private note';}if(g==='busy')uiBusy=true;if(g==='calculating')calculating=true;window.beforeDraft=JSON.stringify(draft);},guard);
   await page.locator('#usePreset').click();
   assert.equal(await page.evaluate(()=>JSON.stringify(draft)===window.beforeDraft&&JSON.stringify(active)===window.originalActive&&window.calls.length===0),true,guard);
   if(guard==='journal')assert.equal(await page.locator('#reasoning').inputValue(),'Unsaved private note');checks[guard+'_guard']=true;
  }
  await setup();await page.locator('#usePreset').click();assert.match(await page.locator('#status').textContent(),/Select an illustrative/);assert.equal(await page.evaluate(()=>JSON.stringify(active)===window.originalActive&&!dirty),true);checks.selection_required=true;
  await setup();await page.evaluate(()=>ctx.inspection.input_years.pop());await page.selectOption('#illustrativePreset','growth');await page.locator('#usePreset').click();assert.match(await page.locator('#status').textContent(),/13-input, 21-year/);assert.equal(await page.evaluate(()=>!dirty&&active.id==='saved'),true);checks.invalid_profile_refused=true;
  await setup();await page.locator('#newZero').click();assert.equal(await page.evaluate(()=>JSON.stringify(draft)===JSON.stringify(ctx.zero)),true);await page.locator('#newImported').click();assert.equal(await page.evaluate(()=>JSON.stringify(draft)===JSON.stringify(ctx.imported)),true);checks.existing_controls_preserved=true;
  await setup();await page.selectOption('#illustrativePreset','growth');await page.locator('#usePreset').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>active===null&&dirty),true);checks.keyboard_activation=true;
  await page.setViewportSize({width:390,height:844});await page.locator('#presetOptions').screenshot({path:path.join(out,'illustrative-starting-points-narrow.png')});assert.equal(await page.locator('#presetOptions').evaluate(e=>e.scrollWidth<=e.clientWidth),true);checks.narrow_layout_fits=true;
  await setup();await page.selectOption('#illustrativePreset','growth');await page.locator('#usePreset').click();await page.locator('#discard').click();
  assert.equal(await page.evaluate(()=>!dirty&&active===null&&JSON.stringify(draft)===JSON.stringify(ctx.zero)&&$('name').value===''&&$('shareLabel').value==='Scenario'&&$('illustrativePreset').value===''),true);checks.discard_clears_preset_identity=true;
  assert.equal(await page.evaluate(()=>comparison===null&&$('calcState').textContent===''&&$('comparisonTable').innerHTML===''&&$('comparisonEvidence').innerHTML===''&&$('chart').classList.contains('hidden')),true);checks.discard_clears_stale_results=true;
  await page.evaluate(()=>{request=async(p,data)=>{if(p==='/api/save'){window.savedPayload=structuredClone(data);return {id:'new-zero',revision:1,...data};}return {scenarios:[]};};});await page.locator('#name').fill('Zero adjustments');await page.locator('#save').click();await page.waitForFunction(()=>!uiBusy);
  assert.equal(await page.evaluate(()=>window.savedPayload.name==='Zero adjustments'&&window.savedPayload.share_label==='Scenario'&&JSON.stringify(window.savedPayload.definition)===JSON.stringify(ctx.zero)),true);checks.save_after_discard_not_mislabeled=true;
  await setup();await page.evaluate(()=>{window.existing=structuredClone(active);window.existing.name='Saved original';window.existing.share_label='Original';request=async()=>({scenario:window.existing,reasoning:[],run:null});});await page.locator('#name').fill('Unsaved rename');await page.locator('#discard').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>active.id==='saved'&&!dirty&&$('name').value==='Saved original'&&$('shareLabel').value==='Original'&&JSON.stringify(draft)===JSON.stringify(window.existing.definition)),true);checks.saved_case_discard_restores_original=true;
  assert.match(await page.locator('#status').textContent(),/Unsaved edits discarded\. Restored Saved original \(revision 1\)/);checks.saved_discard_status_current=true;
  await setup();await page.selectOption('#illustrativePreset','growth');await page.locator('#usePreset').click();await page.locator('#discard').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.locator('#status').textContent(),'Unsaved changes discarded. New zero-adjustment draft.');checks.new_discard_status_current=true;
  await page.evaluate(()=>{window.savedCase={id:'saved',revision:3,name:'Existing saved case',share_label:'Saved case',definition:structuredClone(ctx.zero)};ctx.scenarios=[window.savedCase];renderCases();request=async()=>({scenario:window.savedCase,reasoning:[],run:null});});await page.locator('[data-edit="saved"]').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.locator('#status').textContent(),'Opened saved scenario: Existing saved case (revision 3).');checks.reopened_case_status_current=true;
  await page.evaluate(()=>{request=async p=>p==='/api/reasoning'?{}:{scenario:window.savedCase,reasoning:[],run:null};document.querySelector('#reasoning').closest('details').open=true;});await page.locator('#reasoning').fill('Synthetic note');await page.locator('#saveReasoning').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.locator('#status').textContent(),'Private journal revision saved. It will not enter shared exports.');checks.journal_completion_status_preserved=true;
  await page.evaluate(()=>{request=async p=>p==='/api/calculate'?{job_id:'synthetic'}:p.startsWith('/api/job')?{status:'complete',scenario_id:'saved',evidence:{calculation:'computed_unverified'}}:{scenario:window.savedCase,reasoning:[],run:null};});await page.locator('#calculate').click();await page.waitForFunction(()=>!calculating);assert.equal(await page.locator('#status').textContent(),'Calculation complete. Saved-value checks matched; fresh Excel verification is pending.');checks.calculation_completion_status_preserved=true;
  await page.evaluate(()=>{request=async(p,data)=>p==='/api/save'?{...window.savedCase,...data,revision:4}: {scenarios:[window.savedCase]};});await page.locator('#name').fill('Edited name');await page.locator('#save').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.locator('#status').textContent(),'Scenario saved. Calculate this revision to compare it.');checks.save_completion_status_preserved=true;
  await page.evaluate(async()=>{request=async()=>({scenario:window.savedCase,reasoning:[],run:null});status('Caller owns this progress message.');await withBusy(()=>openCase('saved'));});assert.equal(await page.locator('#status').textContent(),'Caller owns this progress message.');checks.background_open_preserves_caller_status=true;

  const contextSetup=async()=>{await setup();await page.evaluate(()=>{$('baselineContent').classList.remove('hidden');$('baselineEmpty').classList.add('hidden');$('identity').innerHTML='<span class=small>SHA-256 workbook identity</span><br><code>'+sha+'</code>';renderContext();selection=new Set(['saved']);$('comparator').innerHTML='<option value="saved">Saved</option>';window.contextFixture=structuredClone(ctx);window.originalNumeric=JSON.stringify(draft);window.savedForContext={...active,name:'Saved case',share_label:'Saved'};window.responseForContext=()=>({workbook_sha256:sha,chart_context:structuredClone(contextRecord),comparator_id:'saved',runs:[{scenario_id:'saved',share_label:'Saved',result:{points:[{metric:'ext_pv_gdp',year:2032,units:'percent',reference_baseline:1,scenario:2}]}}]});});};
  await contextSetup();assert.equal(await page.locator('#chartContextLabel').inputValue(),'');checks.context_default_absent=true;
  await page.evaluate(()=>{$('reasoning').value='Private draft';journalDirty=true;});await page.locator('#chartContextLabel').fill('Budget: FY2032/33');assert.equal(await page.evaluate(()=>contextDirty&&!dirty&&!$('calculate').disabled&&JSON.stringify(draft)===window.originalNumeric&&$('reasoning').value==='Private draft'&&journalDirty),true);checks.context_edit_independent_numeric_journal=true;
  assert.equal(await page.locator('#workbookSelect').isDisabled(),true);checks.unsaved_label_disables_source_selector=true;
  await page.locator('#compareButton').click();assert.match(await page.locator('#status').textContent(),/chart label/);await page.locator('#pdf').click();assert.match(await page.locator('#status').textContent(),/chart label/);assert.equal(await page.evaluate(()=>window.calls.length),0);checks.unsaved_label_blocks_compare_export=true;
  await contextSetup();await page.locator('#name').fill('Unsaved numerical name');await page.evaluate(()=>{$('reasoning').value='Private draft';journalDirty=true;});await page.locator('#chartContextLabel').fill('Budget: FY2032/33');
  await page.evaluate(()=>{request=(p,data)=>{window.labelPayload=structuredClone(data);return new Promise(r=>window.finishLabel=r);};});await page.locator('#saveChartContext').click();assert.equal(await page.locator('#chartContextLabel').isDisabled()&&await page.locator('#name').isDisabled(),true);checks.label_save_disables_actual_controls=true;
  await page.evaluate(()=>window.finishLabel({workbook_sha256:sha,label:'Budget: FY2032/33',revision:1}));await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>window.labelPayload.workbook_sha===sha&&window.labelPayload.expected_revision===0&&window.labelPayload.label==='Budget: FY2032/33'&&Object.keys(window.labelPayload).length===3),true);checks.label_save_request_bound=true;
  assert.equal(await page.evaluate(()=>!contextDirty&&contextRecord.revision===1&&dirty&&$('name').value==='Unsaved numerical name'&&$('reasoning').value==='Private draft'&&journalDirty&&JSON.stringify(draft)===window.originalNumeric),true);checks.label_save_preserves_unsaved_inputs_journal=true;
  await page.locator('#chartContextLabel').fill('Discard this');await page.evaluate(()=>{request=async()=>({...window.contextFixture,chart_context:{workbook_sha256:sha,label:'Current saved label',revision:2}});});await page.locator('#discardChartContext').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>!contextDirty&&contextRecord.revision===2&&$('chartContextLabel').value==='Current saved label'&&dirty&&$('name').value==='Unsaved numerical name'&&journalDirty&&$('reasoning').value==='Private draft'),true);checks.label_discard_refresh_preserves_inputs_journal=true;
  await contextSetup();await page.locator('#chartContextLabel').fill('Keep my draft');await page.evaluate(()=>{request=async()=>{throw Error('The chart context changed. Reload it before saving or exporting.');};});await page.locator('#saveChartContext').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>contextDirty&&$('chartContextLabel').value==='Keep my draft'&&contextRecord.revision===0),true);assert.match(await page.locator('#status').textContent(),/chart context changed/);checks.context_conflict_preserves_draft=true;
  await contextSetup();await page.evaluate(()=>{window.A='a'.repeat(64);window.B='a'.repeat(12)+'b'.repeat(52);window.loads={};request=p=>new Promise(r=>window.loads[p.split('sha=')[1]]=r);window.loadingA=loadWorkbook(window.A);});assert.equal(await page.evaluate(()=>ctx===null&&contextRecord===null&&$('chartContextLabel').value===''&&$('chart').classList.contains('hidden')),true);checks.source_load_immediately_clears_old_context=true;
  await page.evaluate(()=>{window.loadingB=loadWorkbook(window.B);window.loads[window.B]({...window.contextFixture,chart_context:{workbook_sha256:window.B,label:'Second source',revision:7}});});await page.waitForFunction(()=>ctx!==null);await page.evaluate(()=>window.loads[window.A]({...window.contextFixture,chart_context:{workbook_sha256:window.A,label:'Late first source',revision:8}}));await page.evaluate(()=>window.loadingA);assert.equal(await page.evaluate(()=>sha===window.B&&contextRecord.workbook_sha256===window.B&&$('chartContextLabel').value==='Second source'),true);checks.late_same_prefix_source_cannot_repaint=true;
  await contextSetup();await page.evaluate(()=>{request=(p,data)=>{window.comparePayload=structuredClone(data);return new Promise(r=>window.finishCompare=r);};});await page.locator('#compareButton').click();assert.equal(await page.locator('#chartContextLabel').isDisabled()&&await page.locator('#comparator').isDisabled(),true);checks.compare_disables_actual_context_and_selection=true;
  await page.evaluate(()=>{window.heldComparison=window.responseForContext();$('chartContextLabel').value='New unsaved context';$('chartContextLabel').dispatchEvent(new Event('input',{bubbles:true}));window.finishCompare(window.heldComparison);});await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>comparison===null&&$('comparisonTable').innerHTML===''),true);checks.late_comparison_after_context_edit_discarded=true;
  await contextSetup();await page.evaluate(()=>{request=(p,data)=>{window.comparePayload=structuredClone(data);return Promise.resolve(window.responseForContext());};});await page.locator('#compareButton').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>window.comparePayload.workbook_sha===sha&&window.comparePayload.expected_chart_context_revision===0&&comparison.chart_context.revision===0&&$('comparisonTable').textContent.includes('2032')),true);checks.valid_compare_context_bound=true;
  await contextSetup();await page.evaluate(()=>{request=()=>new Promise(r=>window.finishCompare=r);});await page.locator('#compareButton').click();await page.evaluate(()=>{const r=window.responseForContext();selection=new Set(['other']);clearComparison();window.finishCompare(r);});await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>comparison===null),true);checks.late_comparison_selection_discarded=true;
  await contextSetup();await page.evaluate(()=>{request=()=>new Promise(r=>window.finishExport=r);});await page.locator('#preview').click();assert.equal(await page.locator('#view').isDisabled()&&await page.locator('#workbookSelect').isDisabled(),true);checks.export_disables_actual_view_and_source=true;
  await page.evaluate(()=>{window.finishExport({blob:()=>new Promise(r=>window.finishBlob=r)});});await page.waitForFunction(()=>typeof window.finishBlob==='function');await page.evaluate(()=>{sourceGeneration++;sha='b'.repeat(64);clearComparison();window.finishBlob(new Blob(['never display']));});await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>chartURL===null&&$('chart').classList.contains('hidden')),true);checks.late_export_blob_source_discarded=true;
  await contextSetup();await page.locator('#chartContextLabel').fill('Label during calculation');await page.evaluate(()=>{request=async p=>p==='/api/calculate'?{job_id:'synthetic'}:p.startsWith('/api/job')?{status:'complete',scenario_id:'saved',evidence:{calculation:'computed_unverified'}}:{scenario:window.savedForContext,reasoning:[],run:null};});await page.locator('#calculate').click();await page.waitForFunction(()=>!calculating);assert.equal(await page.evaluate(()=>contextDirty&&$('chartContextLabel').value==='Label during calculation'&&!dirty&&active.id==='saved'),true);checks.calculation_refresh_preserves_context_draft=true;

  await contextSetup();await page.locator('#chartContextLabel').fill('x'.repeat(81));await page.locator('#saveChartContext').click();await page.waitForFunction(()=>!uiBusy);assert.match(await page.locator('#status').textContent(),/no more than 80/);assert.equal(await page.evaluate(()=>contextDirty&&window.calls.length===0),true);checks.context_81_codepoints_refused=true;
  await contextSetup();await page.locator('#chartContextLabel').fill('😀'.repeat(80));await page.evaluate(()=>{request=async(p,data)=>{window.unicodePayload=data;return {workbook_sha256:sha,label:data.label,revision:1};};});await page.locator('#saveChartContext').click();await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>Array.from(contextRecord.label).length===80&&!contextDirty),true);checks.context_80_unicode_codepoints_allowed=true;
  await contextSetup();await page.evaluate(()=>{contextRecord={workbook_sha256:sha,label:'$value <b>literal</b> — FY2032/33',revision:1};renderContext();});assert.equal(await page.locator('#chartContextLabel').inputValue(),'$value <b>literal</b> — FY2032/33');assert.equal(await page.locator('#chartContextLabel b').count(),0);checks.context_literal_not_markup=true;
  await contextSetup();await page.evaluate(()=>{request=()=>new Promise(r=>window.finishCompare=r);});await page.locator('#compareButton').click();await page.evaluate(()=>{const r=window.responseForContext();contextRecord.revision=1;window.finishCompare(r);});await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>comparison?.old===true),true);checks.late_comparison_context_revision_discarded=true;
  await contextSetup();await page.evaluate(()=>{request=async(p,data)=>{window.exportPayload=data;throw Error('The chart context changed. Reload it before saving or exporting.');};});await page.locator('#pdf').click();await page.waitForFunction(()=>!uiBusy);assert.match(await page.locator('#status').textContent(),/chart context changed/);assert.equal(await page.evaluate(()=>window.exportPayload.workbook_sha===sha&&window.exportPayload.expected_chart_context_revision===0&&contextRecord.revision===0&&!dirty&&!contextDirty),true);checks.stale_export_conflict_no_unseen_context=true;
  await contextSetup();await page.locator('#chartContextLabel').fill('Pending first label');await page.evaluate(()=>{request=()=>new Promise(r=>window.finishLabel=r);});await page.locator('#saveChartContext').click();await page.evaluate(()=>{sourceGeneration++;sha='b'.repeat(64);contextRecord={workbook_sha256:sha,label:'Second workbook label',revision:2};renderContext();window.finishLabel({workbook_sha256:'a'.repeat(64),label:'Late label',revision:1});});await page.waitForFunction(()=>!uiBusy);assert.equal(await page.locator('#chartContextLabel').inputValue(),'Second workbook label');checks.late_label_save_cannot_repaint_source=true;
  await contextSetup();await page.evaluate(()=>{request=()=>new Promise((resolve,reject)=>window.failCompare=reject);});await page.locator('#compareButton').click();await page.evaluate(()=>{sourceGeneration++;sha='b'.repeat(64);status('Second workbook loaded.');window.failCompare(Error('Old source failure'));});await page.waitForFunction(()=>!uiBusy);assert.equal(await page.locator('#status').textContent(),'Second workbook loaded.');checks.late_error_cannot_repaint_source_status=true;
  await contextSetup();await page.evaluate(()=>{$('view').value='standard';window.beforeView={table:$('comparisonTable').innerHTML,evidence:$('comparisonEvidence').innerHTML,comparison:JSON.stringify(comparison),generation:comparisonGeneration};chartURL=URL.createObjectURL(new Blob(['synthetic']));$('chart').src=chartURL;});await page.selectOption('#view','briefing');assert.equal(await page.evaluate(()=>$('comparisonTable').innerHTML===window.beforeView.table&&$('comparisonEvidence').innerHTML===window.beforeView.evidence&&JSON.stringify(comparison)===window.beforeView.comparison&&comparisonGeneration===window.beforeView.generation+1&&chartURL===null&&$('chart').classList.contains('hidden')&&!$('chart').hasAttribute('src')),true);checks.view_switch_keeps_numbers_invalidates_preview=true;
  await contextSetup();await page.evaluate(()=>{request=()=>new Promise(r=>window.finishViewExport=r);});await page.locator('#preview').click();await page.evaluate(()=>{$('view').value=$('view').value==='briefing'?'standard':'briefing';$('view').dispatchEvent(new Event('change'));window.finishViewExport({blob:async()=>new Blob(['late view'])});});await page.waitForFunction(()=>!uiBusy);assert.equal(await page.evaluate(()=>chartURL===null&&$('chart').classList.contains('hidden')&&$('comparisonTable').textContent==='Old results'),true);checks.late_view_preview_ignored_table_retained=true;
  await contextSetup();await page.locator('#chartContextLabel').fill('Résumé — FY2032/33');await page.setViewportSize({width:1440,height:1000});await page.locator('#baseline').screenshot({path:path.join(out,'context-editor.png')});await page.setViewportSize({width:390,height:844});await page.locator('#baseline').screenshot({path:path.join(out,'context-editor-narrow.png')});
  fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed:true,checks,mode:'Isolated real headless Chrome with synthetic API fixtures; no workbook, calculation or external request'},null,2));
  console.log(JSON.stringify({passed:true,count:Object.keys(checks).length,output:out}));
 }finally{await browser.close();fs.rmSync(profile,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
