const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../src/lic_dsf/web.html'),'utf8');
const begin=html.indexOf('// Scenario exchange v1:');assert(begin>=0);
const js=html.slice(begin,html.indexOf('</script>',begin));
const rows=['11','13','15','17','20','22','24','28','30','32','34','36','38'];
const inspection={workbook_sha256:'a'.repeat(64),input_years:Array.from({length:21},(_,i)=>2024+i)};
const definition={delta_paths:Object.fromEntries(rows.map(r=>[r,Array(21).fill(0)])),terms:{rate:.08,grace_years:4,maturity_years:9}};
const pack={format:'lic-dsf-scenario-v1',workbook_sha256:inspection.workbook_sha256,input_years:inspection.input_years,definition,share_label:'Illustrative example',shared_rationale:{'20':'Assumed, not a forecast.'}};
function setup(){const elements={};const $=id=>elements[id]??={value:'',files:[],textContent:''};let downloads=0;const s={structuredClone,JSON,Array,Object,Number,Error,Blob,$,act:f=>f(),sourceGeneration:1,sha:inspection.workbook_sha256,ctx:{inspection,zero:definition},active:{id:'savedid',revision:1},dirty:false,calculating:false,journalDirty:false,contextDirty:false,sharedNotes:{},currentRun:true,draft:{old:true},editorReference:{old:true},sourceCurrent:t=>t.sha===s.sha&&t.generation===s.sourceGeneration,canSwitch:()=>!s.dirty&&!s.journalDirty&&!s.contextDirty,clearComparison:()=>{s.comparison=null},renderEditor:()=>{},status:()=>{},document:{createElement:()=>({click:()=>downloads++})},URL:{createObjectURL:b=>{s.lastBlob=b;return'blob:test'},revokeObjectURL:()=>{}},setTimeout:()=>{},request:async()=>({scenario:{id:'savedid',revision:1,definition,share_label:pack.share_label,shared_rationale:pack.shared_rationale,private_journal:'NEVER EXPORT',name:'PRIVATE INTERNAL NAME'}})};vm.createContext(s);vm.runInContext(js,s);s.elements=elements;s.downloads=()=>downloads;return s}
let count=0;function good(name,f){f();count++;}
good('valid exact numeric roundtrip',()=>{let s=setup();assert.deepEqual(JSON.parse(JSON.stringify(s.validateScenarioFile(pack,inspection))),pack)});
for(const [name,edit] of [
 ['version',p=>p.format='unknown'],['workbook',p=>p.workbook_sha256='b'.repeat(64)],['years',p=>p.input_years[0]=2000],['missing row',p=>delete p.definition.delta_paths['11']],['short path',p=>p.definition.delta_paths['11'].pop()],['blank',p=>p.definition.delta_paths['11'][0]=''],['boolean',p=>p.definition.delta_paths['11'][0]=true],['nonfinite',p=>p.definition.delta_paths['11'][0]=Infinity],['result injection',p=>p.results={}],['extra terms',p=>p.definition.terms.extra=1],['fractional grace',p=>p.definition.terms.grace_years=.5],['maturity',p=>p.definition.terms.maturity_years=4],['negative rate',p=>p.definition.terms.rate=-.1],['reserved label',p=>p.share_label='Reference baseline'],['path label',p=>p.share_label='/home/private'],['long label',p=>p.share_label='x'.repeat(41)],['unknown notes',p=>p.shared_rationale.private_journal='secret'],['long note',p=>p.shared_rationale['20']='x'.repeat(1501)]
])good(name,()=>{const p=structuredClone(pack);edit(p);assert.throws(()=>setup().validateScenarioFile(p,inspection));});
for(const character of ['\u200b','\u202e','\u2028','\u2029','\ud800','\u00a0','\ue000','\u0378'])good('backend rejects nonprintable '+JSON.stringify(character),()=>{const p=structuredClone(pack);p.shared_rationale['20']='a'+character+'b';assert.throws(()=>setup().validateScenarioFile(p,inspection),/plain-text/);});
good('printable international text and newline accepted',()=>{const p=structuredClone(pack);p.shared_rationale['20']='Café: naïve assumption.\nΔ = 0.2; 你好; 😀';assert.deepEqual(setup().validateScenarioFile(p,inspection),p);});
(async()=>{
 let s=setup();s.$('calcState').textContent='Current calculation available. Fresh Excel verification pending.';s.$('scenarioFile').files=[{size:500,text:async()=>JSON.stringify(pack)}];await s.importScenarioFile();assert.equal(s.active,null);assert(s.dirty);assert.equal(s.currentRun,false);assert.equal(s.$('calcState').textContent,'Imported draft. Save and calculate this scenario to get results.');assert.deepEqual(s.draft,pack.definition);assert.equal(s.$('name').value,pack.share_label);count++;
 for(const which of ['dirty','journalDirty','contextDirty','calculating']){s=setup();s[which]=true;s.$('scenarioFile').files=[{size:500,text:async()=>JSON.stringify(pack)}];await s.importScenarioFile();assert.equal(s.active.id,'savedid');count++;}
 s=setup();s.$('scenarioFile').files=[{size:131073,text:async()=>{throw Error('Must not read oversized file')}}];await assert.rejects(s.importScenarioFile(),/128 KB/);assert.equal(s.active.id,'savedid');count++;
 s=setup();s.$('scenarioFile').files=[{size:5,text:async()=>'{invalid'}];await assert.rejects(s.importScenarioFile(),/not valid/);assert.equal(s.active.id,'savedid');count++;
 s=setup();s.$('scenarioFile').files=[{size:500,text:async()=>{s.sourceGeneration++;return JSON.stringify(pack)}}];await s.importScenarioFile();assert.equal(s.active.id,'savedid');count++;
 s=setup();await s.downloadScenarioFile();const exported=JSON.parse(await s.lastBlob.text());assert.deepEqual(exported,pack);assert(!JSON.stringify(exported).includes('PRIVATE'));assert.equal(s.downloads(),1);count++;
 s=setup();s.request=async()=>({scenario:{revision:2}});await assert.rejects(s.downloadScenarioFile(),/another tab/);assert.equal(s.downloads(),0);count++;
 s=setup();s.request=async()=>{s.sourceGeneration++;return {scenario:{revision:1}}};await s.downloadScenarioFile();assert.equal(s.downloads(),0);count++;
 console.log(count+' scenario exchange validation/state checks passed. No browser acceptance claimed.');
})().catch(e=>{console.error(e);process.exitCode=1});
